---
# https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md
# https://github.com/openshift/installer/blob/master/docs/dev/dependencies.md
- name: Install build dependencies
  become: true
  package:
    state: latest
    name:
      - golang-bin
      - gcc-c++

- name: Add kvm-common yum repository
  become: true
  yum_repository:
    name: kvm-common
    baseurl: http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/
    description: From https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

- name: Install libvirt and qemu packages
  become: true
  package:
    state: latest
    name:
      - libvirt
      - libvirt-devel
      - libvirt-daemon-kvm
      - qemu-kvm

- name: Give wheel users access to libvirt
  become: true
  copy:
    src: 80-libvirt.rules
    dest: /etc/polkit-1/rules.d/80-libvirt.rules
    owner: root
    group: root
    mode: 0644

- name: Enable IP forwarding now
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Enable IP forwarding after reboot
  become: true
  copy:
    src: sysctl-99-ipforward.conf
    dest: /etc/sysctl.d/99-ipforward.conf
    owner: root
    group: root
    mode: 0644

- name: Turn off TLS
  become: true
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^#listen_tls = 0"
    line: "listen_tls = 0"
  notify:
    - restart libvirtd

- name: Turn on TCP
  become: true
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^#listen_tcp = 1"
    line: "listen_tcp = 1"
  notify:
    - restart libvirtd

- name: Turn off auth for TCP
  become: true
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^#auth_tcp = \"sasl\""
    line: "auth_tcp = \"none\""
  notify:
    - restart libvirtd

- name: Set TCP port
  become: true
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^#tcp_port = \"16509\""
    line: "tcp_port = \"16509\""
  notify:
    - restart libvirtd

- name: Set --listen argument
  become: true
  lineinfile:
    path: /etc/sysconfig/libvirtd
    regexp: "^#LIBVIRTD_ARGS=\"--listen\""
    line: "LIBVIRTD_ARGS=\"--listen\""
  notify:
    - restart libvirtd

- name: Start libvirtd
  become: true
  service:
    name: libvirtd
    state: started
    enabled: true
