---
- name: restart libvirtd
  become: true
  service:
    name: libvirtd
    state: restarted

- name: build storage pool
  become: true
  virt_pool:
    command: build
    name: default

- name: start storage pool
  become: true
  virt_pool:
    command: start
    name: default

- name: reload NetworkManager
  become: true
  service:
    name: NetworkManager
    state: reloaded
